name: flutterproiecttest1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
