// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXE25PTjDaTeDgz21riEzcJrNHXC6j6hA',
    appId: '1:923155973908:web:aa3f7b55f1dbcaac8ee401',
    messagingSenderId: '923155973908',
    projectId: 'flutterappandroid-beabb',
    authDomain: 'flutterappandroid-beabb.firebaseapp.com',
    storageBucket: 'flutterappandroid-beabb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGZaSyoq6wUwAg7ePky3dTfaQXBnsbBw',
    appId: '1:923155973908:android:8832cd3c8f77dc828ee401',
    messagingSenderId: '923155973908',
    projectId: 'flutterappandroid-beabb',
    storageBucket: 'flutterappandroid-beabb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV7EpcYw-46FlTp1mmOjSOrgdXz0bkJMk',
    appId: '1:923155973908:ios:3a19ae7634f22a7e8ee401',
    messagingSenderId: '923155973908',
    projectId: 'flutterappandroid-beabb',
    storageBucket: 'flutterappandroid-beabb.appspot.com',
    iosBundleId: 'com.example.flutterproiecttest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV7EpcYw-46FlTp1mmOjSOrgdXz0bkJMk',
    appId: '1:923155973908:ios:830e1d5de5b406068ee401',
    messagingSenderId: '923155973908',
    projectId: 'flutterappandroid-beabb',
    storageBucket: 'flutterappandroid-beabb.appspot.com',
    iosBundleId: 'com.example.flutterproiecttest1.RunnerTests',
  );
}
